BrewingSite/Models/Brewday.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrewingSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Brewday
    {
        public int id { get; set; }
        public string recipeName { get; set; }
        public string authorId { get; set; }
        public string authorName { get; set; }
        public Nullable<int> styleId { get; set; }
        public Nullable<double> batchSize { get; set; }
        public Nullable<double> boilTime { get; set; }
        public Nullable<int> equipmentProfileId { get; set; }
        public string mashSpargeType { get; set; }
        public Nullable<int> fermentationProfileId { get; set; }
        public Nullable<bool> publicRead { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
        public Nullable<int> originalRecipeId { get; set; }
    }
}

BrewingSite/Controllers/BrewdayController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BrewingSite.Models;

namespace BrewingSite.Controllers
{
    public class BrewdayController : Controller
    {
        brewappEntities dbConn = new brewappEntities();

        // GET: Brewday/x
        [Authorize]
        public ActionResult Index(string id="-1")
        {
            if (id == "-1")
                return Redirect("/Dashboard/Index/8");

            BrewdayViewmodel brewday = new BrewdayViewmodel(dbConn.Brewdays.Find(Convert.ToInt32(id)));
            return View(brewday);
        }

        //GET: Brewday/Create/x
        [Authorize]
        public ActionResult Create(string id = "-1")
        {
            if (id == "-1")
                return Redirect("/Dashboard/Index/8");

            BrewdayViewmodel newBrewday;

            try
            {
                Recipe inputRecipe = dbConn.Recipes.Find(Convert.ToInt32(id));
                newBrewday = new BrewdayViewmodel(inputRecipe);
            }
            catch (Exception ex)
            {
                return Redirect("/Dashboard/Index/" + ex.Message);
            }
            return Redirect("/Brewday/" + newBrewday.brewday.id);
        }

        [HttpPost]
        [Authorize]
        public ActionResult Delete(string id = "-1")
        {
            if (id == "-1")
                return Redirect("/Dashboard/Index/8");

            dbConn.Brewdays.Remove(dbConn.Brewdays.Find(Convert.ToInt32(id)));
            dbConn.SaveChanges();
            return Redirect("/Dashboard/Index/");
            
        }

        public ActionResult ShowLogFermenterGravityDialog(string id = "-1")
        {
            BrewdayMeasurement measurement;

            measurement = dbConn.BrewdayMeasurements.Find(Convert.ToInt32(id));

            return PartialView("_LogFermenterGravity", measurement);
        }

        public ActionResult ShowLogFinalGravityDialog(string id = "-1")
        {
            BrewdayMeasurement measurement;

            measurement = dbConn.BrewdayMeasurements.Find(Convert.ToInt32(id));

            return PartialView("_LogFinalGravity", measurement);
        }

        public ActionResult ShowLogPreboilGravityDialog(string id = "-1")
        {
            BrewdayMeasurement measurement;

            measurement = dbConn.BrewdayMeasurements.Find(Convert.ToInt32(id));

            return PartialView("_LogPreboilGravity", measurement);
        }






        [HttpPost]
        public string logPreboilGravity(BrewdayMeasurement measure, string id = "-1")
        {
            if(id == "-1")
            {
                Response.StatusCode = 404;
                return "No Brewday specified";
            }

            Brewday brewday = dbConn.Brewdays.Find(Convert.ToInt32(id));

            BrewdayMeasurement measurement = (from measures in dbConn.BrewdayMeasurements where measures.brewdayId == brewday.id select measures).FirstOrDefault();

            double calcPoints = (double)(measurement.fermenterGravityCalc / brewday.batchSize);


            measurement.preboilGravityReal = measure.preboilGravityReal;
            measurement.preboilGravityVolume = measure.preboilGravityVolume;
            measurement.preboilGravityTimestamp = DateTime.Now;

            dbConn.BrewdayMeasurements.Attach(measurement);
            dbConn.Entry(measurement).State = System.Data.Entity.EntityState.Modified;
            dbConn.SaveChanges();

            Response.StatusCode = 200;

            return null;
        }

        [HttpPost]
        public string logFermenterGravity(BrewdayMeasurement measure,  string id = "-1")
        {
            if (id == "-1")
            {
                Response.StatusCode = 404;
                return "No Brewday specified";
            }

            try
            {
                Brewday brewday = dbConn.Brewdays.Find(Convert.ToInt32(id));

                BrewdayMeasurement measurement = (from measures in dbConn.BrewdayMeasurements where measures.brewdayId == brewday.id select measures).FirstOrDefault();

                //Get amount of points per gallon expected
                double calcPoints = (double)(((measurement.fermenterGravityCalc - 1) * 1000) * brewday.batchSize);

                //Calculate points per gallon of input data
                double realPoints = (double)(((measure.fermenterGravityReal - 1) * 1000) * measure.fermenterGravityVolume);

                measurement.fermenterGravityDeviation = ((realPoints - calcPoints) / calcPoints) * 100;
                measurement.fermenterGravityReal = measure.fermenterGravityReal;
                measurement.fermenterGravityVolume = measure.fermenterGravityVolume;
                measurement.fermenterGravityTimestamp = DateTime.Now;

                dbConn.BrewdayMeasurements.Attach(measurement);
                dbConn.Entry(measurement).State = System.Data.Entity.EntityState.Modified;
                dbConn.SaveChanges();

                Response.StatusCode = 200;

                return null;
            }
            catch (Exception ex)
            {
                Response.StatusCode = 501;
                return ex.Message;
            }
        }

        [HttpPost]
        public string logFinalGravity(BrewdayMeasurement measure, string id = "-1")
        {
            if (id == "-1")
            {
                Response.StatusCode = 404;
                return "No Brewday specified";
            }

            try
            {
                Brewday brewday = dbConn.Brewdays.Find(Convert.ToInt32(id));

                BrewdayMeasurement measurement = (from measures in dbConn.BrewdayMeasurements where measures.brewdayId == brewday.id select measures).FirstOrDefault();

                //Get amount of points per gallon expected
                double calcPoints = (double)(((measurement.finalGravityCalc - 1) * 1000) * brewday.batchSize);

                //Calculate points per gallon of input data
                double realPoints = (double)(((measure.finalGravityReal - 1) * 1000) * measure.finalGravityVolume);

                measurement.finalGravityDeviation = ((realPoints - calcPoints) / calcPoints) * 100;
                measurement.finalGravityReal = measure.finalGravityReal;
                measurement.finalGravityVolume = measure.finalGravityVolume;
                measurement.finalGravityTimestamp = DateTime.Now;

                dbConn.BrewdayMeasurements.Attach(measurement);
                dbConn.Entry(measurement).State = System.Data.Entity.EntityState.Modified;
                dbConn.SaveChanges();

                Response.StatusCode = 200;

                return null;
            }
            catch (Exception ex)
            {
                Response.StatusCode = 501;
                return ex.Message;
            }
        }
    }
}

BrewingSite/Views/Brewday/MeasurementsPane.cshtml
@model BrewingSite.Models.BrewdayMeasurement

BrewingSite/Views/Brewday/_LogFermenterGravity.cshtml
@model BrewingSite.Models.BrewdayMeasurement

@using (Html.BeginForm("logFermenterGravity", "Brewday"))
{
    @Html.AntiForgeryToken()
    
    <table class="table">
        <tr>
            <td>Fermenter OG</td>
            <td>
                @Html.EditorFor(model => model.fermenterGravityReal, new { htmlAttributes = new { @class = "form-control", @style = "width: 240px" } })
                @Html.ValidationMessageFor(model => model.fermenterGravityReal, "", new { @class = "text-danger" })
            </td>
        </tr>
        <tr>
            <td>Fermenter Volume (gal)</td>
            <td>
                @Html.EditorFor(model => model.fermenterGravityVolume, new { htmlAttributes = new { @class = "form-control", @style = "width: 240px" } })
                @Html.ValidationMessageFor(model => model.fermenterGravityVolume, "", new { @class = "text-danger" })
            </td>
        </tr>

    </table>

}

BrewingSite/Views/Brewday/_LogFinalGravity.cshtml
@model BrewingSite.Models.BrewdayMeasurement

@using (Html.BeginForm("logFinalGravity", "Brewday"))
{
    @Html.AntiForgeryToken()
    
    <table class="table">
        <tr>
            <td>Fermenter FG</td>
            <td>
                @Html.EditorFor(model => model.finalGravityReal, new { htmlAttributes = new { @class = "form-control", @style = "width: 240px" } })
                @Html.ValidationMessageFor(model => model.finalGravityReal, "", new { @class = "text-danger" })
            </td>
        </tr>
        <tr>
            <td>Fermenter Volume (gal)</td>
            <td>
                @Html.EditorFor(model => model.finalGravityVolume, new { htmlAttributes = new { @class = "form-control", @style = "width: 240px" } })
                @Html.ValidationMessageFor(model => model.finalGravityVolume, "", new { @class = "text-danger" })
            </td>
        </tr>

    </table>

}

BrewingSite/Views/Brewday/_LogPreboilGravity.cshtml
@model BrewingSite.Models.BrewdayMeasurement

@using (Html.BeginForm("logPreboilGravity", "Brewday"))
{
    @Html.AntiForgeryToken()
    
    <table class="table">
        <tr>
            <td>Preboil Gravity</td>
            <td>
                @Html.EditorFor(model => model.preboilGravityReal, new { htmlAttributes = new { @class = "form-control", @style = "width: 240px" } })
                @Html.ValidationMessageFor(model => model.preboilGravityReal, "", new { @class = "text-danger" })
            </td>
        </tr>
        <tr>
            <td>Preboil Volume (gal)</td>
            <td>
                @Html.EditorFor(model => model.preboilGravityVolume, new { htmlAttributes = new { @class = "form-control", @style = "width: 240px" } })
                @Html.ValidationMessageFor(model => model.preboilGravityVolume, "", new { @class = "text-danger" })
            </td>
        </tr>

    </table>

}